instrumentation:
  root: .
  default-excludes: true
  excludes:
    - '.idea/**'
    - 'build/**'
  embed-source: false
  complete-copy: false
  include-all-sources: true
reporting:
  print: summary
  reports:
    - lcov
    - cobertura
  dir: ./build/coverage
  watermarks:
    statements: [75, 100]
    lines: [75, 100]
    functions: [99, 100]
    branches: [50, 100]
